# Generated by Django 3.1.1 on 2020-09-21 06:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_registro', models.IntegerField(unique=True, verbose_name='Numero de registro')),
                ('fecha_exp', models.DateField(verbose_name='Expiracion')),
                ('fecha_man', models.DateField(verbose_name='Mantenimiento')),
                ('tammts', models.IntegerField(verbose_name='Tamaño (mts)')),
                ('km', models.IntegerField(verbose_name='Km')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
                ('radio', models.BooleanField(null=True, verbose_name='Radio')),
            ],
            options={
                'verbose_name': 'Camion',
                'verbose_name_plural': 'Camiones',
                'db_table': 'camiones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Companias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('calleav', models.CharField(max_length=255, verbose_name='Calle/Avenida')),
            ],
            options={
                'verbose_name': 'Compañia',
                'verbose_name_plural': 'Compañias',
                'db_table': 'companias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Lugares_Dir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('c', 'ciudad'), ('e', 'estado')], max_length=1, verbose_name='Tipo')),
                ('id_lugar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alquiler.lugares_dir')),
            ],
            options={
                'verbose_name': 'Lugar/Direcion',
                'verbose_name_plural': 'Lugares/Direciones',
                'db_table': 'lugar_dir',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Oficinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('calleav', models.CharField(max_length=255, verbose_name='Calle/Avenida')),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.lugares_dir')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'db_table': 'oficinas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Remolques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_registro', models.IntegerField(unique=True, verbose_name='Numero de registro')),
                ('fecha_exp', models.DateField(verbose_name='Expiracion')),
                ('fecha_man', models.DateField(verbose_name='Mantenimiento')),
                ('tammts', models.IntegerField(verbose_name='Tamaño (mts)')),
                ('material', models.CharField(max_length=255, verbose_name='Material')),
                ('abierto', models.BooleanField(null=True, verbose_name='Abierto')),
                ('id_oficina', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='alquiler.oficinas')),
            ],
            options={
                'verbose_name': 'Remolque',
                'verbose_name_plural': 'Remolques',
                'db_table': 'remolques',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Particulares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellido1', models.CharField(max_length=255, verbose_name='Apellido 1')),
                ('apellido2', models.CharField(max_length=255, verbose_name='Apellido 2')),
                ('calleav', models.CharField(max_length=255, verbose_name='Calle/Avenida')),
                ('tip_lic', models.IntegerField(choices=[(4, 'Tipo 4'), (5, 'Tipo 5')], max_length=1, verbose_name='Tipo de licencia')),
                ('fecha_exp', models.DateField(verbose_name='Fecha exp')),
                ('riesgo', models.BooleanField(null=True, verbose_name='Riesgo')),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.lugares_dir')),
            ],
            options={
                'verbose_name': 'Particular',
                'verbose_name_plural': 'particulares',
                'db_table': 'particulares',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contrartos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alquiler', models.DateField(verbose_name='Alquiler')),
                ('dura', models.IntegerField(verbose_name='Duracion')),
                ('deposito', models.IntegerField(verbose_name='Deposito')),
                ('tar_dia', models.IntegerField(verbose_name='Tarifa/Dia')),
                ('id_camion', models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, to='alquiler.camiones')),
                ('id_compa', models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, to='alquiler.companias')),
                ('id_ofic_destino', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='id_ofic_destino', to='alquiler.oficinas')),
                ('id_ofic_origen', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='id_ofic_origen', to='alquiler.oficinas')),
                ('id_per', models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, to='alquiler.particulares')),
                ('id_remolque', models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, to='alquiler.remolques')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contratos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='companias',
            name='id_ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.lugares_dir'),
        ),
        migrations.AddField(
            model_name='camiones',
            name='id_oficina',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, to='alquiler.oficinas'),
        ),
    ]
