# Generated by Django 3.1.1 on 2020-09-21 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugares_dir',
            name='id_lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alquiler.lugares_dir'),
        ),
    ]
