# Generated by Django 3.1.1 on 2020-09-21 07:21

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0002_auto_20200921_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiones',
            name='radio',
            field=models.BooleanField(blank=True, null=True, verbose_name='Radio'),
        ),
        migrations.AlterField(
            model_name='companias',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contrartos',
            name='id_camion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='alquiler.camiones'),
        ),
        migrations.AlterField(
            model_name='contrartos',
            name='id_compa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='alquiler.companias'),
        ),
        migrations.AlterField(
            model_name='contrartos',
            name='id_per',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='alquiler.particulares'),
        ),
        migrations.AlterField(
            model_name='contrartos',
            name='id_remolque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='alquiler.remolques'),
        ),
        migrations.AlterField(
            model_name='oficinas',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='particulares',
            name='riesgo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Riesgo'),
        ),
        migrations.AlterField(
            model_name='remolques',
            name='abierto',
            field=models.BooleanField(blank=True, null=True, verbose_name='Abierto'),
        ),
    ]
