# Generated by Django 3.1.1 on 2020-09-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0004_auto_20200921_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='companias',
            name='codigo',
            field=models.IntegerField(default=0, unique=True, verbose_name='Codigo'),
        ),
        migrations.AddField(
            model_name='particulares',
            name='dni',
            field=models.IntegerField(default=0, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='camiones',
            name='fecha_exp',
            field=models.DateField(verbose_name='Vencimiento de registro'),
        ),
        migrations.AlterField(
            model_name='camiones',
            name='km',
            field=models.IntegerField(verbose_name='Km actual'),
        ),
        migrations.AlterField(
            model_name='camiones',
            name='tammts',
            field=models.IntegerField(choices=[(18, '18 mts'), (12, '12 mts'), (5, '5 mts')], verbose_name='Tamaño (mts)'),
        ),
        migrations.AlterField(
            model_name='remolques',
            name='fecha_exp',
            field=models.DateField(verbose_name='Vencimiento de registro'),
        ),
        migrations.AlterField(
            model_name='remolques',
            name='tammts',
            field=models.IntegerField(choices=[(4, '4 mts'), (2, '2 mts')], verbose_name='Tamaño (mts)'),
        ),
    ]
